version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "calculator"
s3_bucket = "aws-sam-cli"
s3_prefix = "calculator"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
