AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Sample Calculator

Globals:
  Function:
    Timeout: 3

Resources:
  SumCalculatorFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: function/
      Handler: entrypoint.sum
      Runtime: python3.8
      Events:
        SumCalculator:
          Type: Api
          Properties:
            Path: /sum
            Method: post

Outputs:
  SumCalculatorApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/sum/"